/*
Copyright The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/ai-dynamo/grove/operator/api/core/v1alpha1"
	scheme "github.com/ai-dynamo/grove/operator/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PodCliquesGetter has a method to return a PodCliqueInterface.
// A group's client should implement this interface.
type PodCliquesGetter interface {
	PodCliques(namespace string) PodCliqueInterface
}

// PodCliqueInterface has methods to work with PodClique resources.
type PodCliqueInterface interface {
	Create(ctx context.Context, podClique *corev1alpha1.PodClique, opts v1.CreateOptions) (*corev1alpha1.PodClique, error)
	Update(ctx context.Context, podClique *corev1alpha1.PodClique, opts v1.UpdateOptions) (*corev1alpha1.PodClique, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, podClique *corev1alpha1.PodClique, opts v1.UpdateOptions) (*corev1alpha1.PodClique, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.PodClique, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.PodCliqueList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.PodClique, err error)
	PodCliqueExpansion
}

// podCliques implements PodCliqueInterface
type podCliques struct {
	*gentype.ClientWithList[*corev1alpha1.PodClique, *corev1alpha1.PodCliqueList]
}

// newPodCliques returns a PodCliques
func newPodCliques(c *GroveV1alpha1Client, namespace string) *podCliques {
	return &podCliques{
		gentype.NewClientWithList[*corev1alpha1.PodClique, *corev1alpha1.PodCliqueList](
			"podcliques",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.PodClique { return &corev1alpha1.PodClique{} },
			func() *corev1alpha1.PodCliqueList { return &corev1alpha1.PodCliqueList{} },
		),
	}
}
