/*
Copyright 2025 The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/NVIDIA/grove/operator/api/core/v1alpha1"
	scheme "github.com/NVIDIA/grove/operator/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PodGangSetsGetter has a method to return a PodGangSetInterface.
// A group's client should implement this interface.
type PodGangSetsGetter interface {
	PodGangSets(namespace string) PodGangSetInterface
}

// PodGangSetInterface has methods to work with PodGangSet resources.
type PodGangSetInterface interface {
	Create(ctx context.Context, podGangSet *corev1alpha1.PodGangSet, opts v1.CreateOptions) (*corev1alpha1.PodGangSet, error)
	Update(ctx context.Context, podGangSet *corev1alpha1.PodGangSet, opts v1.UpdateOptions) (*corev1alpha1.PodGangSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, podGangSet *corev1alpha1.PodGangSet, opts v1.UpdateOptions) (*corev1alpha1.PodGangSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.PodGangSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.PodGangSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.PodGangSet, err error)
	PodGangSetExpansion
}

// podGangSets implements PodGangSetInterface
type podGangSets struct {
	*gentype.ClientWithList[*corev1alpha1.PodGangSet, *corev1alpha1.PodGangSetList]
}

// newPodGangSets returns a PodGangSets
func newPodGangSets(c *GroveV1alpha1Client, namespace string) *podGangSets {
	return &podGangSets{
		gentype.NewClientWithList[*corev1alpha1.PodGangSet, *corev1alpha1.PodGangSetList](
			"podgangsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.PodGangSet { return &corev1alpha1.PodGangSet{} },
			func() *corev1alpha1.PodGangSetList { return &corev1alpha1.PodGangSetList{} },
		),
	}
}
