apiVersion: grove.io/v1alpha1
kind: PodGangSet
metadata:
  name: inference
  labels:
    app: inference
spec:
  replicas: 1
  templateSpec:
    cliques:
    - name: decode
      labels:
        "kai.scheduler/queue": "test"
      spec:
        replicas: 2
        podSpec:
          schedulerName: kai-scheduler
          containers:
          - name: decode
            image: nginx:latest
            resources:
              requests:
                cpu: 3
        autoScalingConfig:
          maxReplicas: 5
          metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 80
    - name: prefill-leader
      labels:
        "kai.scheduler/queue": "test"
      spec:
        replicas: 1
        podSpec:
          schedulerName: kai-scheduler
          containers:
          - name: prefill-leader
            image: nginx:latest
            resources:
              requests:
                cpu: 3
    - name: prefill-worker
      labels:
        "kai.scheduler/queue": "test"
      spec:
        replicas: 2
        podSpec:
          schedulerName: kai-scheduler
          containers:
          - name: prefill-worker
            image: nginx:latest
            resources:
              requests:
                cpu: 2
    podCliqueScalingGroups:
      - name: prefill
        cliqueNames:
          - prefill-leader
          - prefill-worker
        scaleConfig:
          maxReplicas: 6
          metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 80
          
