# Workload: PCSG-Only Topology - PCSG with rack constraint
# Test scenario: PCS without constraint, PCSG with rack constraint, standalone clique
---
apiVersion: grove.io/v1alpha1
kind: PodCliqueSet
metadata:
  name: tas-sl-pcsg-only
  labels:
    app: tas-sl-pcsg-only
spec:
  replicas: 1
  template:
    podCliqueScalingGroups:
      - name: workers
        replicas: 2
        minAvailable: 2
        topologyConstraint:
          packDomain: rack
        cliqueNames:
          - worker
    cliques:
      - name: worker
        labels:
          kai.scheduler/queue: test
        spec:
          roleName: worker
          replicas: 1
          minAvailable: 1
          podSpec:
            schedulerName: kai-scheduler
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node_role.e2e.grove.nvidia.com
                          operator: In
                          values:
                            - agent
            tolerations:
              - key: node_role.e2e.grove.nvidia.com
                operator: Equal
                value: agent
                effect: NoSchedule
            containers:
              - name: worker
                image: registry:5001/nginx:alpine-slim
                resources:
                  requests:
                    memory: 30Mi
      - name: router
        labels:
          kai.scheduler/queue: test
        spec:
          roleName: router
          replicas: 2
          minAvailable: 2
          podSpec:
            schedulerName: kai-scheduler
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node_role.e2e.grove.nvidia.com
                          operator: In
                          values:
                            - agent
            tolerations:
              - key: node_role.e2e.grove.nvidia.com
                operator: Equal
                value: agent
                effect: NoSchedule
            containers:
              - name: router
                image: registry:5001/nginx:alpine-slim
                resources:
                  requests:
                    memory: 30Mi
