/*
Copyright 2025 The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/NVIDIA/grove/operator/api/core/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PodCliqueScalingGroupLister helps list PodCliqueScalingGroups.
// All objects returned here must be treated as read-only.
type PodCliqueScalingGroupLister interface {
	// List lists all PodCliqueScalingGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.PodCliqueScalingGroup, err error)
	// PodCliqueScalingGroups returns an object that can list and get PodCliqueScalingGroups.
	PodCliqueScalingGroups(namespace string) PodCliqueScalingGroupNamespaceLister
	PodCliqueScalingGroupListerExpansion
}

// podCliqueScalingGroupLister implements the PodCliqueScalingGroupLister interface.
type podCliqueScalingGroupLister struct {
	listers.ResourceIndexer[*corev1alpha1.PodCliqueScalingGroup]
}

// NewPodCliqueScalingGroupLister returns a new PodCliqueScalingGroupLister.
func NewPodCliqueScalingGroupLister(indexer cache.Indexer) PodCliqueScalingGroupLister {
	return &podCliqueScalingGroupLister{listers.New[*corev1alpha1.PodCliqueScalingGroup](indexer, corev1alpha1.Resource("podcliquescalinggroup"))}
}

// PodCliqueScalingGroups returns an object that can list and get PodCliqueScalingGroups.
func (s *podCliqueScalingGroupLister) PodCliqueScalingGroups(namespace string) PodCliqueScalingGroupNamespaceLister {
	return podCliqueScalingGroupNamespaceLister{listers.NewNamespaced[*corev1alpha1.PodCliqueScalingGroup](s.ResourceIndexer, namespace)}
}

// PodCliqueScalingGroupNamespaceLister helps list and get PodCliqueScalingGroups.
// All objects returned here must be treated as read-only.
type PodCliqueScalingGroupNamespaceLister interface {
	// List lists all PodCliqueScalingGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.PodCliqueScalingGroup, err error)
	// Get retrieves the PodCliqueScalingGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha1.PodCliqueScalingGroup, error)
	PodCliqueScalingGroupNamespaceListerExpansion
}

// podCliqueScalingGroupNamespaceLister implements the PodCliqueScalingGroupNamespaceLister
// interface.
type podCliqueScalingGroupNamespaceLister struct {
	listers.ResourceIndexer[*corev1alpha1.PodCliqueScalingGroup]
}
