/*
Copyright The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/ai-dynamo/grove/operator/api/core/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PodCliqueTemplateSpecRevisionLister helps list PodCliqueTemplateSpecRevisions.
// All objects returned here must be treated as read-only.
type PodCliqueTemplateSpecRevisionLister interface {
	// List lists all PodCliqueTemplateSpecRevisions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.PodCliqueTemplateSpecRevision, err error)
	// PodCliqueTemplateSpecRevisions returns an object that can list and get PodCliqueTemplateSpecRevisions.
	PodCliqueTemplateSpecRevisions(namespace string) PodCliqueTemplateSpecRevisionNamespaceLister
	PodCliqueTemplateSpecRevisionListerExpansion
}

// podCliqueTemplateSpecRevisionLister implements the PodCliqueTemplateSpecRevisionLister interface.
type podCliqueTemplateSpecRevisionLister struct {
	listers.ResourceIndexer[*corev1alpha1.PodCliqueTemplateSpecRevision]
}

// NewPodCliqueTemplateSpecRevisionLister returns a new PodCliqueTemplateSpecRevisionLister.
func NewPodCliqueTemplateSpecRevisionLister(indexer cache.Indexer) PodCliqueTemplateSpecRevisionLister {
	return &podCliqueTemplateSpecRevisionLister{listers.New[*corev1alpha1.PodCliqueTemplateSpecRevision](indexer, corev1alpha1.Resource("podcliquetemplatespecrevision"))}
}

// PodCliqueTemplateSpecRevisions returns an object that can list and get PodCliqueTemplateSpecRevisions.
func (s *podCliqueTemplateSpecRevisionLister) PodCliqueTemplateSpecRevisions(namespace string) PodCliqueTemplateSpecRevisionNamespaceLister {
	return podCliqueTemplateSpecRevisionNamespaceLister{listers.NewNamespaced[*corev1alpha1.PodCliqueTemplateSpecRevision](s.ResourceIndexer, namespace)}
}

// PodCliqueTemplateSpecRevisionNamespaceLister helps list and get PodCliqueTemplateSpecRevisions.
// All objects returned here must be treated as read-only.
type PodCliqueTemplateSpecRevisionNamespaceLister interface {
	// List lists all PodCliqueTemplateSpecRevisions in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.PodCliqueTemplateSpecRevision, err error)
	// Get retrieves the PodCliqueTemplateSpecRevision from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha1.PodCliqueTemplateSpecRevision, error)
	PodCliqueTemplateSpecRevisionNamespaceListerExpansion
}

// podCliqueTemplateSpecRevisionNamespaceLister implements the PodCliqueTemplateSpecRevisionNamespaceLister
// interface.
type podCliqueTemplateSpecRevisionNamespaceLister struct {
	listers.ResourceIndexer[*corev1alpha1.PodCliqueTemplateSpecRevision]
}
