/*
Copyright 2025 The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/NVIDIA/grove/operator/api/core/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// PodCliqueLister helps list PodCliques.
// All objects returned here must be treated as read-only.
type PodCliqueLister interface {
	// List lists all PodCliques in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.PodClique, err error)
	// PodCliques returns an object that can list and get PodCliques.
	PodCliques(namespace string) PodCliqueNamespaceLister
	PodCliqueListerExpansion
}

// podCliqueLister implements the PodCliqueLister interface.
type podCliqueLister struct {
	listers.ResourceIndexer[*v1alpha1.PodClique]
}

// NewPodCliqueLister returns a new PodCliqueLister.
func NewPodCliqueLister(indexer cache.Indexer) PodCliqueLister {
	return &podCliqueLister{listers.New[*v1alpha1.PodClique](indexer, v1alpha1.Resource("podclique"))}
}

// PodCliques returns an object that can list and get PodCliques.
func (s *podCliqueLister) PodCliques(namespace string) PodCliqueNamespaceLister {
	return podCliqueNamespaceLister{listers.NewNamespaced[*v1alpha1.PodClique](s.ResourceIndexer, namespace)}
}

// PodCliqueNamespaceLister helps list and get PodCliques.
// All objects returned here must be treated as read-only.
type PodCliqueNamespaceLister interface {
	// List lists all PodCliques in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.PodClique, err error)
	// Get retrieves the PodClique from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.PodClique, error)
	PodCliqueNamespaceListerExpansion
}

// podCliqueNamespaceLister implements the PodCliqueNamespaceLister
// interface.
type podCliqueNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.PodClique]
}
