/*
Copyright 2025 The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/NVIDIA/grove/operator/api/core/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PodCliqueSetLister helps list PodCliqueSets.
// All objects returned here must be treated as read-only.
type PodCliqueSetLister interface {
	// List lists all PodCliqueSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.PodCliqueSet, err error)
	// PodCliqueSets returns an object that can list and get PodCliqueSets.
	PodCliqueSets(namespace string) PodCliqueSetNamespaceLister
	PodCliqueSetListerExpansion
}

// podCliqueSetLister implements the PodCliqueSetLister interface.
type podCliqueSetLister struct {
	listers.ResourceIndexer[*corev1alpha1.PodCliqueSet]
}

// NewPodCliqueSetLister returns a new PodCliqueSetLister.
func NewPodCliqueSetLister(indexer cache.Indexer) PodCliqueSetLister {
	return &podCliqueSetLister{listers.New[*corev1alpha1.PodCliqueSet](indexer, corev1alpha1.Resource("podcliqueset"))}
}

// PodCliqueSets returns an object that can list and get PodCliqueSets.
func (s *podCliqueSetLister) PodCliqueSets(namespace string) PodCliqueSetNamespaceLister {
	return podCliqueSetNamespaceLister{listers.NewNamespaced[*corev1alpha1.PodCliqueSet](s.ResourceIndexer, namespace)}
}

// PodCliqueSetNamespaceLister helps list and get PodCliqueSets.
// All objects returned here must be treated as read-only.
type PodCliqueSetNamespaceLister interface {
	// List lists all PodCliqueSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.PodCliqueSet, err error)
	// Get retrieves the PodCliqueSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha1.PodCliqueSet, error)
	PodCliqueSetNamespaceListerExpansion
}

// podCliqueSetNamespaceLister implements the PodCliqueSetNamespaceLister
// interface.
type podCliqueSetNamespaceLister struct {
	listers.ResourceIndexer[*corev1alpha1.PodCliqueSet]
}
