/*
Copyright The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apicorev1alpha1 "github.com/ai-dynamo/grove/operator/api/core/v1alpha1"
	versioned "github.com/ai-dynamo/grove/operator/client/clientset/versioned"
	internalinterfaces "github.com/ai-dynamo/grove/operator/client/informers/externalversions/internalinterfaces"
	corev1alpha1 "github.com/ai-dynamo/grove/operator/client/listers/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodCliqueScalingGroupInformer provides access to a shared informer and lister for
// PodCliqueScalingGroups.
type PodCliqueScalingGroupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() corev1alpha1.PodCliqueScalingGroupLister
}

type podCliqueScalingGroupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodCliqueScalingGroupInformer constructs a new informer for PodCliqueScalingGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodCliqueScalingGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodCliqueScalingGroupInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodCliqueScalingGroupInformer constructs a new informer for PodCliqueScalingGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodCliqueScalingGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GroveV1alpha1().PodCliqueScalingGroups(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GroveV1alpha1().PodCliqueScalingGroups(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GroveV1alpha1().PodCliqueScalingGroups(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GroveV1alpha1().PodCliqueScalingGroups(namespace).Watch(ctx, options)
			},
		},
		&apicorev1alpha1.PodCliqueScalingGroup{},
		resyncPeriod,
		indexers,
	)
}

func (f *podCliqueScalingGroupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodCliqueScalingGroupInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podCliqueScalingGroupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apicorev1alpha1.PodCliqueScalingGroup{}, f.defaultInformer)
}

func (f *podCliqueScalingGroupInformer) Lister() corev1alpha1.PodCliqueScalingGroupLister {
	return corev1alpha1.NewPodCliqueScalingGroupLister(f.Informer().GetIndexer())
}
