apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: scheduler
build:
  local: { } # see https://skaffold.dev/docs/builders/build-environments/local/
  artifacts:
    - image: local-skaffold/kube-scheduler
      # context: ..
      # docker:
      #   dockerfile: Dockerfile
      #   buildArgs:
      #     VERSION: "{{.VERSION}}"
    # ko does not work properly, somehow. Fix later as faster builds are a must
      ko:
        dependencies:
          paths:
            - cmd
            - plugins/grovescheduling
            - internal
            - VERSION
        flags:
          - -v
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd
# Deploy will only be used to run the scheduler as the second scheduler
deploy:
  helm:
    releases:
      - name: kube-scheduler
        chartPath: charts
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_local_skaffold_kube_scheduler}}'
          image.tag: '{{.IMAGE_TAG_local_skaffold_kube_scheduler}}@{{.IMAGE_DIGEST_local_skaffold_kube_scheduler}}'
        skipBuildDependencies: true
        createNamespace: true
        wait: false
profiles:
  - name: debug
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          replicaCount: 1
          config.leaderElection.enabled: false
  # - name: kind
  #   deploy:
  #     helm:
  #       releases:
  #         - name: grove-kube-scheduler
  #           chartPath: charts
  #           setValueTemplates:
  #             image.repository: '{{.IMAGE_REPO_local_skaffold_grove_scheduler}}'
  #             image.tag: '{{.IMAGE_TAG_local_skaffold_grove_scheduler}}@{{.IMAGE_DIGEST_local_skaffold_grove_scheduler}}'
  #             kubeconfig: /etc/kubernetes/kubeconfig
