# Example: Multi-Node Aggregated Inference
# Documentation: docs/user-guide/01_core-concepts/03_pcsg_intro.md
#
# Demonstrates PodCliqueScalingGroup for multi-node deployments with a
# leader-worker topology. Scaling the PCSG replicates the entire unit
# (1 leader + N workers) while preserving the ratio.
#
# NOTE: This example uses fake-node tolerations for the local KIND demo cluster
# created with `make kind-up FAKE_NODES=40`. Remove the tolerations when deploying
# to a real cluster.
---
apiVersion: grove.io/v1alpha1
kind: PodCliqueSet
metadata:
  name: multinode-aggregated
  namespace: default
spec:
  replicas: 1
  template:
    cliques:
    - name: leader
      spec:
        roleName: leader
        replicas: 1
        podSpec:
          tolerations:
          - key: fake-node
            operator: Equal
            value: "true"
            effect: NoSchedule
          containers:
          - name: model-leader
            image: nginx:latest
            command: ["/bin/sh"]
            args: ["-c", "echo 'Model Leader (Aggregated) on node:' && hostname && sleep infinity"]
            resources:
              requests:
                cpu: "10m"
                memory: "32Mi"
    - name: worker
      spec:
        roleName: worker
        replicas: 3
        podSpec:
          tolerations:
          - key: fake-node
            operator: Equal
            value: "true"
            effect: NoSchedule
          containers:
          - name: model-worker
            image: nginx:latest
            command: ["/bin/sh"]
            args: ["-c", "echo 'Model Worker (Aggregated) on node:' && hostname && sleep infinity"]
            resources:
              requests:
                cpu: "10m"
                memory: "32Mi"
    podCliqueScalingGroups:
    - name: model-instance
      cliqueNames: [leader, worker]
      replicas: 2