# Example: Single-Node Aggregated Inference
# Documentation: docs/user-guide/01_core-concepts/02_pcs_and_pclq_intro.md
#
# Demonstrates a simple PodCliqueSet with a single standalone PodClique where
# each pod is a complete model instance that can service requests independently.
#
# NOTE: This example uses fake-node tolerations for the local KIND demo cluster
# created with `make kind-up FAKE_NODES=40`. Remove the tolerations when deploying
# to a real cluster.
---
apiVersion: grove.io/v1alpha1
kind: PodCliqueSet
metadata:
  name: single-node-aggregated
  namespace: default
spec:
  replicas: 1
  template:
    cliques:
    - name: model-worker
      spec:
        roleName: model-worker
        replicas: 2
        podSpec:
          tolerations:
          - key: fake-node
            operator: Equal
            value: "true"
            effect: NoSchedule
          containers:
          - name: model-worker
            image: nginx:latest
            command: ["/bin/sh"]
            args: ["-c", "echo 'Model Worker (Aggregated) on node:' && hostname && sleep infinity"]
            resources:
              requests:
                cpu: "10m"
                memory: "32Mi"