/*
Copyright 2025 The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/ai-dynamo/grove/scheduler/api/core/v1alpha1"
	scheme "github.com/ai-dynamo/grove/scheduler/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PodGangsGetter has a method to return a PodGangInterface.
// A group's client should implement this interface.
type PodGangsGetter interface {
	PodGangs(namespace string) PodGangInterface
}

// PodGangInterface has methods to work with PodGang resources.
type PodGangInterface interface {
	Create(ctx context.Context, podGang *corev1alpha1.PodGang, opts v1.CreateOptions) (*corev1alpha1.PodGang, error)
	Update(ctx context.Context, podGang *corev1alpha1.PodGang, opts v1.UpdateOptions) (*corev1alpha1.PodGang, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, podGang *corev1alpha1.PodGang, opts v1.UpdateOptions) (*corev1alpha1.PodGang, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.PodGang, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.PodGangList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.PodGang, err error)
	PodGangExpansion
}

// podGangs implements PodGangInterface
type podGangs struct {
	*gentype.ClientWithList[*corev1alpha1.PodGang, *corev1alpha1.PodGangList]
}

// newPodGangs returns a PodGangs
func newPodGangs(c *SchedulerV1alpha1Client, namespace string) *podGangs {
	return &podGangs{
		gentype.NewClientWithList[*corev1alpha1.PodGang, *corev1alpha1.PodGangList](
			"podgangs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.PodGang { return &corev1alpha1.PodGang{} },
			func() *corev1alpha1.PodGangList { return &corev1alpha1.PodGangList{} },
		),
	}
}
