//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2025 The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v2 "k8s.io/api/autoscaling/v2"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingConfig) DeepCopyInto(out *AutoScalingConfig) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]v2.MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingConfig.
func (in *AutoScalingConfig) DeepCopy() *AutoScalingConfig {
	if in == nil {
		return nil
	}
	out := new(AutoScalingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadlessServiceConfig) DeepCopyInto(out *HeadlessServiceConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadlessServiceConfig.
func (in *HeadlessServiceConfig) DeepCopy() *HeadlessServiceConfig {
	if in == nil {
		return nil
	}
	out := new(HeadlessServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastError) DeepCopyInto(out *LastError) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastError.
func (in *LastError) DeepCopy() *LastError {
	if in == nil {
		return nil
	}
	out := new(LastError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastOperation) DeepCopyInto(out *LastOperation) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastOperation.
func (in *LastOperation) DeepCopy() *LastOperation {
	if in == nil {
		return nil
	}
	out := new(LastOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPackGroupConfig) DeepCopyInto(out *NetworkPackGroupConfig) {
	*out = *in
	if in.CliqueNames != nil {
		in, out := &in.CliqueNames, &out.CliqueNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPackGroupConfig.
func (in *NetworkPackGroupConfig) DeepCopy() *NetworkPackGroupConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkPackGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodClique) DeepCopyInto(out *PodClique) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodClique.
func (in *PodClique) DeepCopy() *PodClique {
	if in == nil {
		return nil
	}
	out := new(PodClique)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodClique) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueList) DeepCopyInto(out *PodCliqueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodClique, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueList.
func (in *PodCliqueList) DeepCopy() *PodCliqueList {
	if in == nil {
		return nil
	}
	out := new(PodCliqueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodCliqueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueRollingUpdateProgress) DeepCopyInto(out *PodCliqueRollingUpdateProgress) {
	*out = *in
	in.UpdateStartedAt.DeepCopyInto(&out.UpdateStartedAt)
	if in.UpdateEndedAt != nil {
		in, out := &in.UpdateEndedAt, &out.UpdateEndedAt
		*out = (*in).DeepCopy()
	}
	if in.ReadyPodsSelectedToUpdate != nil {
		in, out := &in.ReadyPodsSelectedToUpdate, &out.ReadyPodsSelectedToUpdate
		*out = new(PodsSelectedToUpdate)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueRollingUpdateProgress.
func (in *PodCliqueRollingUpdateProgress) DeepCopy() *PodCliqueRollingUpdateProgress {
	if in == nil {
		return nil
	}
	out := new(PodCliqueRollingUpdateProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueScalingGroup) DeepCopyInto(out *PodCliqueScalingGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueScalingGroup.
func (in *PodCliqueScalingGroup) DeepCopy() *PodCliqueScalingGroup {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodCliqueScalingGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueScalingGroupConfig) DeepCopyInto(out *PodCliqueScalingGroupConfig) {
	*out = *in
	if in.CliqueNames != nil {
		in, out := &in.CliqueNames, &out.CliqueNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(int32)
		**out = **in
	}
	if in.ScaleConfig != nil {
		in, out := &in.ScaleConfig, &out.ScaleConfig
		*out = new(AutoScalingConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueScalingGroupConfig.
func (in *PodCliqueScalingGroupConfig) DeepCopy() *PodCliqueScalingGroupConfig {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueScalingGroupList) DeepCopyInto(out *PodCliqueScalingGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodCliqueScalingGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueScalingGroupList.
func (in *PodCliqueScalingGroupList) DeepCopy() *PodCliqueScalingGroupList {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodCliqueScalingGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueScalingGroupReplicaRollingUpdateProgress) DeepCopyInto(out *PodCliqueScalingGroupReplicaRollingUpdateProgress) {
	*out = *in
	in.UpdateStartedAt.DeepCopyInto(&out.UpdateStartedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueScalingGroupReplicaRollingUpdateProgress.
func (in *PodCliqueScalingGroupReplicaRollingUpdateProgress) DeepCopy() *PodCliqueScalingGroupReplicaRollingUpdateProgress {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroupReplicaRollingUpdateProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueScalingGroupRollingUpdateProgress) DeepCopyInto(out *PodCliqueScalingGroupRollingUpdateProgress) {
	*out = *in
	in.UpdateStartedAt.DeepCopyInto(&out.UpdateStartedAt)
	if in.UpdateEndedAt != nil {
		in, out := &in.UpdateEndedAt, &out.UpdateEndedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedPodCliques != nil {
		in, out := &in.UpdatedPodCliques, &out.UpdatedPodCliques
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CurrentlyUpdating != nil {
		in, out := &in.CurrentlyUpdating, &out.CurrentlyUpdating
		*out = new(PodCliqueScalingGroupReplicaRollingUpdateProgress)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueScalingGroupRollingUpdateProgress.
func (in *PodCliqueScalingGroupRollingUpdateProgress) DeepCopy() *PodCliqueScalingGroupRollingUpdateProgress {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroupRollingUpdateProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueScalingGroupSpec) DeepCopyInto(out *PodCliqueScalingGroupSpec) {
	*out = *in
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(int32)
		**out = **in
	}
	if in.CliqueNames != nil {
		in, out := &in.CliqueNames, &out.CliqueNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueScalingGroupSpec.
func (in *PodCliqueScalingGroupSpec) DeepCopy() *PodCliqueScalingGroupSpec {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueScalingGroupStatus) DeepCopyInto(out *PodCliqueScalingGroupStatus) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(string)
		**out = **in
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.LastOperation != nil {
		in, out := &in.LastOperation, &out.LastOperation
		*out = new(LastOperation)
		(*in).DeepCopyInto(*out)
	}
	if in.LastErrors != nil {
		in, out := &in.LastErrors, &out.LastErrors
		*out = make([]LastError, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CurrentPodGangSetGenerationHash != nil {
		in, out := &in.CurrentPodGangSetGenerationHash, &out.CurrentPodGangSetGenerationHash
		*out = new(string)
		**out = **in
	}
	if in.RollingUpdateProgress != nil {
		in, out := &in.RollingUpdateProgress, &out.RollingUpdateProgress
		*out = new(PodCliqueScalingGroupRollingUpdateProgress)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueScalingGroupStatus.
func (in *PodCliqueScalingGroupStatus) DeepCopy() *PodCliqueScalingGroupStatus {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueSpec) DeepCopyInto(out *PodCliqueSpec) {
	*out = *in
	in.PodSpec.DeepCopyInto(&out.PodSpec)
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(int32)
		**out = **in
	}
	if in.StartsAfter != nil {
		in, out := &in.StartsAfter, &out.StartsAfter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ScaleConfig != nil {
		in, out := &in.ScaleConfig, &out.ScaleConfig
		*out = new(AutoScalingConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueSpec.
func (in *PodCliqueSpec) DeepCopy() *PodCliqueSpec {
	if in == nil {
		return nil
	}
	out := new(PodCliqueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueStatus) DeepCopyInto(out *PodCliqueStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.LastOperation != nil {
		in, out := &in.LastOperation, &out.LastOperation
		*out = new(LastOperation)
		(*in).DeepCopyInto(*out)
	}
	if in.LastErrors != nil {
		in, out := &in.LastErrors, &out.LastErrors
		*out = make([]LastError, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CurrentPodGangSetGenerationHash != nil {
		in, out := &in.CurrentPodGangSetGenerationHash, &out.CurrentPodGangSetGenerationHash
		*out = new(string)
		**out = **in
	}
	if in.RollingUpdateProgress != nil {
		in, out := &in.RollingUpdateProgress, &out.RollingUpdateProgress
		*out = new(PodCliqueRollingUpdateProgress)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueStatus.
func (in *PodCliqueStatus) DeepCopy() *PodCliqueStatus {
	if in == nil {
		return nil
	}
	out := new(PodCliqueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueTemplateSpec) DeepCopyInto(out *PodCliqueTemplateSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueTemplateSpec.
func (in *PodCliqueTemplateSpec) DeepCopy() *PodCliqueTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PodCliqueTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGangSet) DeepCopyInto(out *PodGangSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGangSet.
func (in *PodGangSet) DeepCopy() *PodGangSet {
	if in == nil {
		return nil
	}
	out := new(PodGangSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodGangSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGangSetList) DeepCopyInto(out *PodGangSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodGangSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGangSetList.
func (in *PodGangSetList) DeepCopy() *PodGangSetList {
	if in == nil {
		return nil
	}
	out := new(PodGangSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodGangSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGangSetReplicaRollingUpdateProgress) DeepCopyInto(out *PodGangSetReplicaRollingUpdateProgress) {
	*out = *in
	in.UpdateStartedAt.DeepCopyInto(&out.UpdateStartedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGangSetReplicaRollingUpdateProgress.
func (in *PodGangSetReplicaRollingUpdateProgress) DeepCopy() *PodGangSetReplicaRollingUpdateProgress {
	if in == nil {
		return nil
	}
	out := new(PodGangSetReplicaRollingUpdateProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGangSetRollingUpdateProgress) DeepCopyInto(out *PodGangSetRollingUpdateProgress) {
	*out = *in
	in.UpdateStartedAt.DeepCopyInto(&out.UpdateStartedAt)
	if in.UpdateEndedAt != nil {
		in, out := &in.UpdateEndedAt, &out.UpdateEndedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedPodCliqueScalingGroups != nil {
		in, out := &in.UpdatedPodCliqueScalingGroups, &out.UpdatedPodCliqueScalingGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UpdatedPodCliques != nil {
		in, out := &in.UpdatedPodCliques, &out.UpdatedPodCliques
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CurrentlyUpdating != nil {
		in, out := &in.CurrentlyUpdating, &out.CurrentlyUpdating
		*out = new(PodGangSetReplicaRollingUpdateProgress)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGangSetRollingUpdateProgress.
func (in *PodGangSetRollingUpdateProgress) DeepCopy() *PodGangSetRollingUpdateProgress {
	if in == nil {
		return nil
	}
	out := new(PodGangSetRollingUpdateProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGangSetSpec) DeepCopyInto(out *PodGangSetSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	if in.ReplicaSpreadConstraints != nil {
		in, out := &in.ReplicaSpreadConstraints, &out.ReplicaSpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGangSetSpec.
func (in *PodGangSetSpec) DeepCopy() *PodGangSetSpec {
	if in == nil {
		return nil
	}
	out := new(PodGangSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGangSetStatus) DeepCopyInto(out *PodGangSetStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.LastOperation != nil {
		in, out := &in.LastOperation, &out.LastOperation
		*out = new(LastOperation)
		(*in).DeepCopyInto(*out)
	}
	if in.LastErrors != nil {
		in, out := &in.LastErrors, &out.LastErrors
		*out = make([]LastError, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(string)
		**out = **in
	}
	if in.PodGangStatutes != nil {
		in, out := &in.PodGangStatutes, &out.PodGangStatutes
		*out = make([]PodGangStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CurrentGenerationHash != nil {
		in, out := &in.CurrentGenerationHash, &out.CurrentGenerationHash
		*out = new(string)
		**out = **in
	}
	if in.RollingUpdateProgress != nil {
		in, out := &in.RollingUpdateProgress, &out.RollingUpdateProgress
		*out = new(PodGangSetRollingUpdateProgress)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGangSetStatus.
func (in *PodGangSetStatus) DeepCopy() *PodGangSetStatus {
	if in == nil {
		return nil
	}
	out := new(PodGangSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGangSetTemplateSpec) DeepCopyInto(out *PodGangSetTemplateSpec) {
	*out = *in
	if in.Cliques != nil {
		in, out := &in.Cliques, &out.Cliques
		*out = make([]*PodCliqueTemplateSpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(PodCliqueTemplateSpec)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.StartupType != nil {
		in, out := &in.StartupType, &out.StartupType
		*out = new(CliqueStartupType)
		**out = **in
	}
	if in.HeadlessServiceConfig != nil {
		in, out := &in.HeadlessServiceConfig, &out.HeadlessServiceConfig
		*out = new(HeadlessServiceConfig)
		**out = **in
	}
	if in.SchedulingPolicyConfig != nil {
		in, out := &in.SchedulingPolicyConfig, &out.SchedulingPolicyConfig
		*out = new(SchedulingPolicyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TerminationDelay != nil {
		in, out := &in.TerminationDelay, &out.TerminationDelay
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PodCliqueScalingGroupConfigs != nil {
		in, out := &in.PodCliqueScalingGroupConfigs, &out.PodCliqueScalingGroupConfigs
		*out = make([]PodCliqueScalingGroupConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGangSetTemplateSpec.
func (in *PodGangSetTemplateSpec) DeepCopy() *PodGangSetTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PodGangSetTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGangStatus) DeepCopyInto(out *PodGangStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGangStatus.
func (in *PodGangStatus) DeepCopy() *PodGangStatus {
	if in == nil {
		return nil
	}
	out := new(PodGangStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodsSelectedToUpdate) DeepCopyInto(out *PodsSelectedToUpdate) {
	*out = *in
	if in.Previous != nil {
		in, out := &in.Previous, &out.Previous
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodsSelectedToUpdate.
func (in *PodsSelectedToUpdate) DeepCopy() *PodsSelectedToUpdate {
	if in == nil {
		return nil
	}
	out := new(PodsSelectedToUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingPolicyConfig) DeepCopyInto(out *SchedulingPolicyConfig) {
	*out = *in
	if in.NetworkPackGroupConfigs != nil {
		in, out := &in.NetworkPackGroupConfigs, &out.NetworkPackGroupConfigs
		*out = make([]NetworkPackGroupConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingPolicyConfig.
func (in *SchedulingPolicyConfig) DeepCopy() *SchedulingPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(SchedulingPolicyConfig)
	in.DeepCopyInto(out)
	return out
}
