# Ignore everyting
**

# Exclude folders/files that are relevant for build
!.git
!hack/
!operator/Dockerfile.dockerignore
!operator/api
!operator/cmd/
!operator/internal/
!operator/initc/
!operator/client/
!operator/hack/
!operator/go.mod
!operator/go.sum
!operator/Makefile
!operator/VERSION
!scheduler/api

# Ignore kind's setup files
operator/hack/kind/
