apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: grove-operator
build:
  artifacts:
    - image: grove-operator
      ko:
        dependencies:
          paths:
            - api
            - cmd
            - initc
            - internal
            - VERSION
        flags:
          - -v
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd
    - image: grove-initc
      ko:
        dependencies:
          paths:
            - api
            - initc
            - internal
            - VERSION
        flags:
          - -v
        main: ./initc/cmd
    - image: grove-install-crds
      ko:
        dependencies:
          paths:
            - api
            - cmd/install-crds
            - internal
            - VERSION
        flags:
          - -v
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/install-crds
  tagPolicy:
    envTemplate:
      template: '{{.VERSION}}'
  local:
    push: true
deploy:
  helm:
    releases:
      - name: grove-operator
        chartPath: charts
        setValueTemplates:
          crdInstaller.image.repository: '{{.IMAGE_REPO_grove_install_crds}}'
          crdInstaller.image.tag: '{{.VERSION}}@{{.IMAGE_DIGEST_grove_install_crds}}'
          deployment.env[0].name: GROVE_INIT_CONTAINER_IMAGE
          deployment.env[0].value: '{{.CONTAINER_REGISTRY}}/grove-initc'
          image.repository: '{{.IMAGE_REPO}}'
          image.tag: '{{.VERSION}}@{{.IMAGE_DIGEST}}'
        createNamespace: true
        wait: true
        skipBuildDependencies: true
profiles:
  - name: debug
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          config:
            leaderElection:
              enabled: false
          replicaCount: 1
  - name: topology-test
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          config:
            leaderElection:
              enabled: false
            scheduler:
              defaultProfileName: kai-scheduler
              profiles:
                - name: kai-scheduler
            topologyAwareScheduling:
              enabled: true
          replicaCount: 1
  - name: mnnvl-test
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          config:
            leaderElection:
              enabled: false
            network:
              autoMNNVLEnabled: true
          replicaCount: 1
